function gameLevelData(level) {

let information;

	if(level===1){

		 information=[
			   [
			    	{
			    		type:'rect',
			    		width:15,
			    		height:15,
			    		position:{
			    			x:2,
			    			y:3
			    		}
			    	},
			    	{
			    		type:'rect',
			    		width:15,
			    		height:20,
			    		position:{
			    			x:33,
			    			y:16
			    		}
			    	},
			    	{
			    		type:'rect',
			    		width:15,
			    		height:20,
			    		position:{
			    			x:3,
			    			y:35
			    		}
			    	},
			    	{
			    		type:'rect',
			    		width:15,
			    		height:19,
			    		position:{
			    			x:24,
			    			y:81
			    		}
			    	},
			    	{
			    		type:'line',
			    		length:16,
			    		orientation:'horizontal',
			    		position:{
			    			x:10,
			    			y:18
			    		}
			    	},
		    		{
			    		type:'line',
			    		length:44,
			    		orientation:'horizontal',
			    		position:{
			    			x:38,
			    			y:36
			    		}
			    	},
			    	{
			    		type:'line',
			    		length:21,
			    		orientation:'vertical',
			    		position:{
			    			x:11,
			    			y:26
			    		}
			    	}
			    ],

			   [
			    	{
			    		name:'enemy',
			    		value:-10,
			    		color:'crimson',
			    		quantity:15
			    	},
			    	{
			    		name:'health',
			    		value:5,
			    		color:'green',
			    		quantity:12
			    	},
			    	{
			    		name:'portal',
			    		value:1,
			    		color:'violet',
			    		quantity:1
			    	},
			    	{
			    		name:'weapon',
			    		value:1,
			    		color:'orange',
			    		quantity:1
			    	},
			    	{
			    		name:'player',
			    		color:'blue',
			    		quantity:1
			    	}
			    ]
			];
	}
	else if(level===2) {

		 information=[
			   [
			    	{
			    		type:'rect',
			    		width:5,
			    		height:35,
			    		position:{
			    			x:3,
			    			y:41
			    		}
			    	},
			    	{
			    		type:'rect',
			    		width:5,
			    		height:35,
			    		position:{
			    			x:13,
			    			y:4
			    		}
			    	},
			    	{
			    		type:'rect',
			    		width:5,
			    		height:35,
			    		position:{
			    			x:33,
			    			y:13
			    		}
			    	},
			    	{
			    		type:'rect',
			    		width:5,
			    		height:25,
			    		position:{
			    			x:22,
			    			y:68
			    		}
			    	},
			    	{
			    		type:'line',
			    		length:12,
			    		orientation:'horizontal',
			    		position:{
			    			x:5,
			    			y:28
			    		}
			    	},
			    	{
			    		type:'line',
			    		length:12,
			    		orientation:'vertical',
			    		position:{
			    			x:9,
			    			y:72
			    		}
			    	},
			    	{
			    		type:'line',
			    		length:6,
			    		orientation:'vertical',
			    		position:{
			    			x:6,
			    			y:28
			    		}
			    	},
			    	{
			    		type:'line',
			    		length:13,
			    		orientation:'vertical',
			    		position:{
			    			x:19,
			    			y:15
			    		}
			    	}
			    ],

			   [
			    	{
			    		name:'enemy',
			    		value:-10,
			    		color:'crimson',
			    		quantity:15
			    	},
			    	{
			    		name:'health',
			    		value:5,
			    		color:'green',
			    		quantity:12
			    	},
			    	{
			    		name:'portal',
			    		value:1,
			    		color:'violet',
			    		quantity:1
			    	},
			    	{
			    		name:'weapon',
			    		value:1,
			    		color:'orange',
			    		quantity:1
			    	},
			    	{
			    		name:'player',
			    		color:'blue',
			    		quantity:1
			    	}
			    ]
			];

	}
	else if(level===3) {

		 information=[
			   [
			    	{
			    		type:'rect',
			    		width:32,
			    		height:37,
			    		position:{
			    			x:16,
			    			y:5
			    		}
			    	},
			    	{
			    		type:'rect',
			    		width:32,
			    		height:31,
			    		position:{
			    			x:4,
			    			y:68
			    		}
			    	},
			    	{
			    		type:'line',
			    		length:25,
			    		orientation:'horizontal',
			    		position:{
			    			x:22,
			    			y:42
			    		}
			    	}
			    ],

			   [
			    	{
			    		name:'enemy',
			    		value:-10,
			    		color:'crimson',
			    		quantity:15
			    	},
			    	{
			    		name:'health',
			    		value:5,
			    		color:'green',
			    		quantity:12
			    	},
			    	{
			    		name:'portal',
			    		value:1,
			    		color:'violet',
			    		quantity:1
			    	},
			    	{
			    		name:'weapon',
			    		value:1,
			    		color:'orange',
			    		quantity:1
			    	},
			    	{
			    		name:'player',
			    		color:'blue',
			    		quantity:1
			    	}
			    ]
			];

	} else if(level===4){

		 information=[
			   [
			    	{
			    		type:'rect',
			    		width:10,
			    		height:10,
			    		position:{
			    			x:2,
			    			y:3
			    		}
			    	},
			    	{
			    		type:'rect',
			    		width:10,
			    		height:10,
			    		position:{
			    			x:20,
			    			y:3
			    		}
			    	},
			    	{
			    		type:'rect',
			    		width:10,
			    		height:10,
			    		position:{
			    			x:35,
			    			y:4
			    		}
			    	},
			    	{
			    		type:'rect',
			    		width:26,
			    		height:20,
			    		position:{
			    			x:10,
			    			y:19
			    		}
			    	},
			    	{
			    		type:'rect',
			    		width:11,
			    		height:10,
			    		position:{
			    			x:4,
			    			y:49
			    		}
			    	},
			    	{
			    		type:'rect',
			    		width:10,
			    		height:10,
			    		position:{
			    			x:36,
			    			y:49
			    		}
			    	},
			    	{
			    		type:'rect',
			    		width:30,
			    		height:20,
			    		position:{
			    			x:13,
			    			y:68
			    		}
			    	},
			    	{
			    		type:'line',
			    		length:8,
			    		orientation:'horizontal',
			    		position:{
			    			x:14,
			    			y:59
			    		}
			    	},
			    	{
			    		type:'line',
			    		length:9,
			    		orientation:'horizontal',
			    		position:{
			    			x:12,
			    			y:39
			    		}
			    	},
			    	{
			    		type:'line',
			    		length:8,
			    		orientation:'horizontal',
			    		position:{
			    			x:11,
			    			y:13
			    		}
			    	},
			    	{
			    		type:'line',
			    		length:6,
			    		orientation:'vertical',
			    		position:{
			    			x:13,
			    			y:7
			    		}
			    	},
			    	{
			    		type:'line',
			    		length:4,
			    		orientation:'vertical',
			    		position:{
			    			x:31,
			    			y:7
			    		}
			    	},
			    	{
			    		type:'line',
			    		length:34,
			    		orientation:'horizontal',
			    		position:{
			    			x:41,
			    			y:14
			    		}
			    	}
			    ],

			   [
			    	{
			    		name:'enemy',
			    		value:-10,
			    		color:'crimson',
			    		quantity:15
			    	},
			    	{
			    		name:'health',
			    		value:5,
			    		color:'green',
			    		quantity:12
			    	},
			    	{
			    		name:'portal',
			    		value:1,
			    		color:'violet',
			    		quantity:1
			    	},
			    	{
			    		name:'weapon',
			    		value:1,
			    		color:'orange',
			    		quantity:1
			    	},
			    	{
			    		name:'player',
			    		color:'blue',
			    		quantity:1
			    	}
			    ]
			];

	}

	return information;

}

module.exports={
	fetchgameData:function(gameLevel) {
		return gameLevelData(gameLevel)
	}
}